import { Recipe } from "./types";

export const recipes: Recipe[] = [
  {
    id: "gratin-pates-jambon",
    name: "Gratin de pâtes au jambon",
    emoji: "🧀",
    gradient: "from-amber-400 to-orange-500",
    moods: ["reconfort"],
    diets: [],
    allergens: ["gluten", "lactose"],
    cuisine: "Française",
    calories: 650,
    timeMinutes: 30,
    cookBudget: 4,
    orderBudget: 14,
    ingredients: [
      { name: "pâtes", quantity: "300 g" },
      { name: "jambon", quantity: "150 g" },
      { name: "crème fraîche", quantity: "20 cl" },
      { name: "gruyère", quantity: "100 g" },
    ],
  },
  {
    id: "salade-quinoa-legumes",
    name: "Salade de quinoa et légumes croquants",
    emoji: "🥗",
    gradient: "from-emerald-400 to-lime-500",
    moods: ["leger", "sale"],
    diets: ["vegan", "vegetarien", "sans_gluten", "sans_lactose"],
    allergens: [],
    cuisine: "Méditerranéenne",
    calories: 380,
    timeMinutes: 20,
    cookBudget: 5,
    orderBudget: 12,
    ingredients: [
      { name: "quinoa", quantity: "150 g" },
      { name: "concombre", quantity: "1" },
      { name: "tomates", quantity: "2" },
      { name: "citron", quantity: "1" },
    ],
  },
  {
    id: "curry-pois-chiches",
    name: "Curry de pois chiches et lait de coco",
    emoji: "🍛",
    gradient: "from-yellow-400 to-amber-600",
    moods: ["reconfort", "sale"],
    diets: ["vegan", "vegetarien", "sans_gluten", "sans_lactose"],
    allergens: [],
    cuisine: "Indienne",
    calories: 520,
    timeMinutes: 35,
    cookBudget: 4,
    orderBudget: 15,
    ingredients: [
      { name: "pois chiches", quantity: "400 g" },
      { name: "lait de coco", quantity: "20 cl" },
      { name: "oignon", quantity: "1" },
      { name: "riz", quantity: "150 g" },
    ],
  },
  {
    id: "saumon-vapeur-brocolis",
    name: "Saumon vapeur, brocolis et riz",
    emoji: "🐟",
    gradient: "from-rose-300 to-pink-500",
    moods: ["leger", "sale"],
    diets: ["sans_gluten", "sans_lactose"],
    allergens: ["fruits_de_mer"],
    cuisine: "Française",
    calories: 420,
    timeMinutes: 25,
    cookBudget: 7,
    orderBudget: 18,
    ingredients: [
      { name: "saumon", quantity: "2 pavés" },
      { name: "brocolis", quantity: "300 g" },
      { name: "riz", quantity: "150 g" },
    ],
  },
  {
    id: "burger-maison",
    name: "Burger maison et frites au four",
    emoji: "🍔",
    gradient: "from-orange-500 to-red-500",
    moods: ["reconfort", "sale"],
    diets: [],
    allergens: ["gluten", "lactose"],
    cuisine: "Américaine",
    calories: 780,
    timeMinutes: 30,
    cookBudget: 6,
    orderBudget: 16,
    ingredients: [
      { name: "pain à burger", quantity: "2" },
      { name: "steak haché", quantity: "2" },
      { name: "cheddar", quantity: "2 tranches" },
      { name: "pommes de terre", quantity: "4" },
    ],
  },
  {
    id: "soupe-legumes-maison",
    name: "Soupe de légumes maison",
    emoji: "🍲",
    gradient: "from-green-400 to-emerald-600",
    moods: ["reconfort", "leger"],
    diets: ["vegan", "vegetarien", "sans_gluten", "sans_lactose"],
    allergens: [],
    cuisine: "Française",
    calories: 220,
    timeMinutes: 25,
    cookBudget: 3,
    orderBudget: 10,
    ingredients: [
      { name: "carottes", quantity: "3" },
      { name: "pommes de terre", quantity: "2" },
      { name: "poireau", quantity: "1" },
      { name: "oignon", quantity: "1" },
    ],
  },
  {
    id: "pad-thai-tofu",
    name: "Pad thaï au tofu",
    emoji: "🍜",
    gradient: "from-amber-300 to-orange-600",
    moods: ["sale"],
    diets: ["vegan", "vegetarien"],
    allergens: ["soja", "arachides"],
    cuisine: "Thaïlandaise",
    calories: 540,
    timeMinutes: 25,
    cookBudget: 6,
    orderBudget: 16,
    ingredients: [
      { name: "nouilles de riz", quantity: "200 g" },
      { name: "tofu", quantity: "200 g" },
      { name: "cacahuètes", quantity: "30 g" },
      { name: "sauce soja", quantity: "3 cas" },
    ],
  },
  {
    id: "omelette-champignons",
    name: "Omelette aux champignons et fromage",
    emoji: "🍳",
    gradient: "from-yellow-300 to-amber-500",
    moods: ["leger", "sale"],
    diets: ["vegetarien", "sans_gluten"],
    allergens: ["oeuf", "lactose"],
    cuisine: "Française",
    calories: 350,
    timeMinutes: 15,
    cookBudget: 3,
    orderBudget: 11,
    ingredients: [
      { name: "œufs", quantity: "4" },
      { name: "champignons", quantity: "200 g" },
      { name: "gruyère", quantity: "50 g" },
    ],
  },
  {
    id: "poke-bowl-poulet",
    name: "Poke bowl au poulet mariné",
    emoji: "🥙",
    gradient: "from-lime-400 to-green-500",
    moods: ["leger", "sale"],
    diets: ["sans_lactose"],
    allergens: ["soja"],
    cuisine: "Hawaïenne",
    calories: 480,
    timeMinutes: 25,
    cookBudget: 6,
    orderBudget: 15,
    ingredients: [
      { name: "blanc de poulet", quantity: "2" },
      { name: "riz", quantity: "150 g" },
      { name: "avocat", quantity: "1" },
      { name: "edamame", quantity: "100 g" },
    ],
  },
  {
    id: "tartiflette",
    name: "Tartiflette savoyarde",
    emoji: "🥔",
    gradient: "from-amber-500 to-yellow-700",
    moods: ["reconfort"],
    diets: ["sans_gluten"],
    allergens: ["lactose"],
    cuisine: "Française",
    calories: 820,
    timeMinutes: 40,
    cookBudget: 6,
    orderBudget: 17,
    ingredients: [
      { name: "pommes de terre", quantity: "1 kg" },
      { name: "reblochon", quantity: "1" },
      { name: "lardons", quantity: "200 g" },
      { name: "oignon", quantity: "1" },
    ],
  },
  {
    id: "tarte-fine-pommes",
    name: "Tarte fine aux pommes",
    emoji: "🍎",
    gradient: "from-rose-300 to-orange-400",
    moods: ["sucre", "leger"],
    diets: ["vegetarien"],
    allergens: ["gluten"],
    cuisine: "Française",
    calories: 290,
    timeMinutes: 35,
    cookBudget: 3,
    orderBudget: 9,
    ingredients: [
      { name: "pâte feuilletée", quantity: "1" },
      { name: "pommes", quantity: "4" },
      { name: "sucre", quantity: "2 cas" },
    ],
  },
  {
    id: "fondant-chocolat",
    name: "Fondant au chocolat",
    emoji: "🍫",
    gradient: "from-amber-700 to-stone-900",
    moods: ["sucre", "reconfort"],
    diets: ["vegetarien"],
    allergens: ["gluten", "oeuf", "lactose"],
    cuisine: "Française",
    calories: 410,
    timeMinutes: 25,
    cookBudget: 4,
    orderBudget: 10,
    ingredients: [
      { name: "chocolat noir", quantity: "200 g" },
      { name: "beurre", quantity: "150 g" },
      { name: "œufs", quantity: "4" },
      { name: "farine", quantity: "50 g" },
    ],
  },
  {
    id: "pancakes-banane",
    name: "Pancakes à la banane",
    emoji: "🥞",
    gradient: "from-yellow-300 to-amber-400",
    moods: ["sucre", "reconfort"],
    diets: ["vegetarien"],
    allergens: ["gluten", "oeuf", "lactose"],
    cuisine: "Américaine",
    calories: 470,
    timeMinutes: 20,
    cookBudget: 3,
    orderBudget: 9,
    ingredients: [
      { name: "farine", quantity: "200 g" },
      { name: "bananes", quantity: "2" },
      { name: "œufs", quantity: "2" },
      { name: "lait", quantity: "20 cl" },
    ],
  },
  {
    id: "buddha-bowl-falafels",
    name: "Buddha bowl falafels et houmous",
    emoji: "🧆",
    gradient: "from-orange-300 to-amber-600",
    moods: ["sale", "leger"],
    diets: ["vegan", "vegetarien"],
    allergens: ["gluten"],
    cuisine: "Moyen-Orientale",
    calories: 510,
    timeMinutes: 25,
    cookBudget: 5,
    orderBudget: 14,
    ingredients: [
      { name: "falafels", quantity: "8" },
      { name: "houmous", quantity: "100 g" },
      { name: "salade", quantity: "1" },
      { name: "tomates", quantity: "2" },
    ],
  },
  {
    id: "pizza-maison",
    name: "Pizza maison margherita",
    emoji: "🍕",
    gradient: "from-red-500 to-rose-600",
    moods: ["reconfort", "sale"],
    diets: ["vegetarien"],
    allergens: ["gluten", "lactose"],
    cuisine: "Italienne",
    calories: 690,
    timeMinutes: 35,
    cookBudget: 4,
    orderBudget: 15,
    ingredients: [
      { name: "pâte à pizza", quantity: "1" },
      { name: "sauce tomate", quantity: "1 bol" },
      { name: "mozzarella", quantity: "150 g" },
      { name: "basilic", quantity: "qq feuilles" },
    ],
  },
  {
    id: "wok-boeuf-legumes",
    name: "Wok de bœuf et légumes croquants",
    emoji: "🥘",
    gradient: "from-red-600 to-orange-700",
    moods: ["sale"],
    diets: ["sans_lactose"],
    allergens: ["soja", "gluten"],
    cuisine: "Asiatique",
    calories: 560,
    timeMinutes: 20,
    cookBudget: 7,
    orderBudget: 16,
    ingredients: [
      { name: "bœuf émincé", quantity: "300 g" },
      { name: "poivrons", quantity: "2" },
      { name: "brocolis", quantity: "200 g" },
      { name: "sauce soja", quantity: "3 cas" },
    ],
  },
  {
    id: "ratatouille-oeuf",
    name: "Ratatouille et œuf au plat",
    emoji: "🍆",
    gradient: "from-purple-400 to-rose-500",
    moods: ["leger", "reconfort"],
    diets: ["vegetarien", "sans_gluten", "sans_lactose"],
    allergens: ["oeuf"],
    cuisine: "Française",
    calories: 340,
    timeMinutes: 40,
    cookBudget: 4,
    orderBudget: 12,
    ingredients: [
      { name: "aubergine", quantity: "1" },
      { name: "courgette", quantity: "1" },
      { name: "tomates", quantity: "3" },
      { name: "œufs", quantity: "2" },
    ],
  },
  {
    id: "risotto-champignons",
    name: "Risotto crémeux aux champignons",
    emoji: "🍚",
    gradient: "from-stone-300 to-amber-400",
    moods: ["reconfort"],
    diets: ["vegetarien", "sans_gluten"],
    allergens: ["lactose"],
    cuisine: "Italienne",
    calories: 600,
    timeMinutes: 35,
    cookBudget: 5,
    orderBudget: 16,
    ingredients: [
      { name: "riz arborio", quantity: "200 g" },
      { name: "champignons", quantity: "250 g" },
      { name: "parmesan", quantity: "50 g" },
      { name: "bouillon de légumes", quantity: "1 L" },
    ],
  },
  {
    id: "smoothie-bowl-fruits",
    name: "Smoothie bowl fruits rouges",
    emoji: "🍓",
    gradient: "from-pink-400 to-rose-500",
    moods: ["sucre", "leger"],
    diets: ["vegan", "vegetarien", "sans_gluten"],
    allergens: ["lactose"],
    cuisine: "Healthy",
    calories: 310,
    timeMinutes: 10,
    cookBudget: 4,
    orderBudget: 9,
    ingredients: [
      { name: "fruits rouges surgelés", quantity: "200 g" },
      { name: "banane", quantity: "1" },
      { name: "yaourt", quantity: "1" },
      { name: "granola", quantity: "30 g" },
    ],
  },
  {
    id: "couscous-legumes",
    name: "Couscous de légumes et merguez",
    emoji: "🌶️",
    gradient: "from-orange-400 to-red-600",
    moods: ["reconfort", "sale"],
    diets: ["sans_lactose"],
    allergens: ["gluten"],
    cuisine: "Maghrébine",
    calories: 640,
    timeMinutes: 45,
    cookBudget: 6,
    orderBudget: 17,
    ingredients: [
      { name: "semoule", quantity: "250 g" },
      { name: "merguez", quantity: "4" },
      { name: "carottes", quantity: "2" },
      { name: "pois chiches", quantity: "200 g" },
    ],
  },
];
